version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - main_net
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "main:999:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - main_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  producer:
    build:
      context: .
      dockerfile: BuildProducer
    environment:
      USE_STDOUT: "true"
    networks:
      - main_net
    depends_on:
      - kafka
      - zookeeper
  consumer:
    build:
      context: .
      dockerfile: BuildCosumer
    environment:
      USE_STDOUT: "true"
    deploy:
      mode: replicated
      replicas: 30
    networks:
      - main_net
    depends_on:
      - kafka
      - zookeeper
networks:
  main_net:
    driver: bridge